Merge with 5.2 flambda-backend
janestreet/merlin-jst pull request #81
Opened 2024-08-14 21:05 UTC by ncik-roberts

(draft, will add description later)

2024-08-18 19:24 UTC, ccasin approved these changes
Looks good, just a question and a nit.

2024-08-20 13:16 UTC, ncik-roberts commented on src/ocaml/typing/typecore.ml
>        raise(Error(loc, !!penv, Pattern_type_clash(err, None)))
Good catch, thanks. I think calls to `unify_pat_types` are guarded with try-with, though one would be forgiven for not spotting that.

2024-08-20 13:24 UTC, ncik-roberts commented on src/ocaml/preprocess/menhirLib.ml
> -let require_20210419 = ()
I think I should try to keep this at 20210419, per Liam's comment here: https://github.com/janestreet/merlin-jst/pull/86

2024-08-20 13:28 UTC, ncik-roberts commented
Thanks for the review. Obviously, it conflicts terribly with the latest merlin roll. This is what I'm going to do:
1. Wait until the flambda-backend 5.2 merge branch has progressed to a better state.
2. Re-import the upstream copy of flambda-backend in this PR and fix conflicts.
3. Merge with origin/main and fix conflicts.

This is a lot of work, so I'm going to hold off until we feel that this PR is close to mergeable.

2024-08-28 18:30 UTC, liam923 requested changes

2024-08-28 18:30 UTC, liam923 commented on upstream/ocaml_flambda/utils/config.common.ml
> -#2 "utils/config.common.ml"
I think something got messed up here

2024-08-28 19:01 UTC, liam923 commented on upstream/ocaml_flambda/utils/config.common.ml
> -#2 "utils/config.common.ml"
`config.common.ml` got replaced with `config.common.ml.in` in flambda. I deleted this file, and added `upstream/ocaml_flambda/configure`, which is the file that now contains the magic numbers

2024-08-28 19:11 UTC, liam923 approved these changes

2024-09-23 14:06 UTC, merged

2024-09-26 14:26 UTC, liam923 commented
After merging, we realized it was a mistake to do a squash-merge instead of a normal merge. We re-wrote history for it to be a normal merge instead - see PR #98